# Generated by Django 5.2.15 on 2026-06-24 15:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Partido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipo_local', models.CharField(max_length=100)),
                ('equipo_visitante', models.CharField(max_length=100)),
                ('fecha_partido', models.DateTimeField()),
                ('goles_local_real', models.IntegerField(blank=True, null=True)),
                ('goles_visitante_real', models.IntegerField(blank=True, null=True)),
                ('finalizado', models.BooleanField(default=False)),
                ('es_partido_especial', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Partido',
                'verbose_name_plural': 'Partidos',
                'ordering': ['fecha_partido'],
            },
        ),
        migrations.CreateModel(
            name='PerfilQuiniela',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntos_totales', models.IntegerField(default=0)),
                ('marcadores_especiales_atinados', models.IntegerField(default=0)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfilquiniela', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil de Quiniela',
                'verbose_name_plural': 'Perfiles de Quiniela',
            },
        ),
        migrations.CreateModel(
            name='Pronostico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goles_local_pronostico', models.IntegerField()),
                ('goles_visitante_pronostico', models.IntegerField()),
                ('puntos_ganados', models.IntegerField(default=0)),
                ('partido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pronosticos', to='quiniela.partido')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pronosticos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pronóstico',
                'verbose_name_plural': 'Pronósticos',
                'unique_together': {('usuario', 'partido')},
            },
        ),
        migrations.CreateModel(
            name='PuntosDiarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('puntos', models.IntegerField(default=0)),
                ('pago_confirmado', models.BooleanField(default=False)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='puntos_diarios', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Puntos Diarios',
                'verbose_name_plural': 'Puntos Diarios',
                'ordering': ['-fecha', '-puntos'],
                'unique_together': {('usuario', 'fecha')},
            },
        ),
    ]
