# Generated by Django 5.2.15 on 2026-06-24 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiniela', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='partido',
            name='codigo_bandera_local',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='Código Bandera Local'),
        ),
        migrations.AddField(
            model_name='partido',
            name='codigo_bandera_visitante',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='Código Bandera Visitante'),
        ),
    ]
