# Generated by Django 5.2.15 on 2026-06-24 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiniela', '0002_partido_codigo_bandera_local_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partido',
            name='codigo_bandera_local',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Código Bandera Local'),
        ),
        migrations.AlterField(
            model_name='partido',
            name='codigo_bandera_visitante',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Código Bandera Visitante'),
        ),
    ]
