# Generated by Django 5.2.15 on 2026-06-25 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiniela', '0003_alter_partido_codigo_bandera_local_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='puntosdiarios',
            name='marcadores_especiales',
            field=models.IntegerField(default=0),
        ),
    ]
