# Generated by Django 5.2.15 on 2026-06-25 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiniela', '0004_puntosdiarios_marcadores_especiales'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionQuiniela',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bloquear_marcadores_repetidos', models.BooleanField(default=True, help_text='Si está activo, no se permitirá que dos usuarios repitan el mismo marcador exacto para un partido.', verbose_name='Bloquear marcadores repetidos')),
            ],
            options={
                'verbose_name': 'Configuración de la Quiniela',
                'verbose_name_plural': 'Configuración de la Quiniela',
            },
        ),
    ]
