# Generated by Django 5.2.15 on 2026-06-25 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiniela', '0005_configuracionquiniela'),
    ]

    operations = [
        migrations.AddField(
            model_name='puntosdiarios',
            name='monto_pagado',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Monto de pago diario registrado para el usuario.', max_digits=10, verbose_name='Monto Pagado'),
        ),
    ]
