# Generated by Django 5.2.15 on 2026-06-30 16:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiniela', '0006_puntosdiarios_monto_pagado'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Torneo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre del Torneo')),
                ('activo', models.BooleanField(default=True, verbose_name='¿Es el Torneo Activo?')),
                ('fecha_inicio', models.DateField(blank=True, null=True)),
                ('fecha_fin', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Torneo',
                'verbose_name_plural': 'Torneos',
            },
        ),
        migrations.AlterModelOptions(
            name='puntosdiarios',
            options={'ordering': ['-fecha', '-puntos', '-marcadores_especiales'], 'verbose_name': 'Puntos Diarios', 'verbose_name_plural': 'Puntos Diarios'},
        ),
        migrations.AddField(
            model_name='partido',
            name='torneo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='partidos', to='quiniela.torneo', verbose_name='Torneo'),
        ),
        migrations.CreateModel(
            name='PuntosTorneoUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntos_totales', models.IntegerField(default=0)),
                ('marcadores_especiales_atinados', models.IntegerField(default=0)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='puntos_torneos', to=settings.AUTH_USER_MODEL)),
                ('torneo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posiciones_usuarios', to='quiniela.torneo')),
            ],
            options={
                'verbose_name': 'Puntos por Torneo',
                'verbose_name_plural': 'Puntos por Torneos',
                'ordering': ['-puntos_totales', '-marcadores_especiales_atinados', 'usuario__username'],
                'unique_together': {('usuario', 'torneo')},
            },
        ),
    ]
