# Generated by Django 5.2.15 on 2026-06-30 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiniela', '0007_torneo_alter_puntosdiarios_options_partido_torneo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='puntostorneousuario',
            name='monto_pagado_acumulado',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Monto Pagado Acumulado'),
        ),
    ]
